name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Push
        run: bash ./src/push.sh
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USERNAME: ${{ secrets.USERNAME }}
          COMMIT_MESSAGE: "Update GitHub-Profile-3D-Contrib"
